### ISSUE TITLE
Feature request: add Tado V3 node the Flow temperature optimalization option

### ISSUE THREAD

**Issue by vampywiz17** [mattdavis90/node-red-contrib-tado-client#80]
Hello there,

I test you node and work well! So i replace my REST api call in HA, because the new auth. method are really complex to able to handle it...

the Energy IQ are working well, but i found that Flow temperature control only set it up to TadoX. 

My device are TadoV3 but also support these feature becaue i use OpenTherm connection. With my old HA config, i use these REST call:

```
  - resource: "https://my.tado.com/api/v2/homes/home_ID/flowTemperatureOptimization"
    scan_interval: 300
    method: GET
    headers:
      Authorization: "Bearer {{ state_attr('sensor.token', 'access_token') }}"
      Accept: "*/*"
    sensor:
      - name: "tado_flow_temperature_max"
        value_template: "{{ value_json.maxFlowTemperature | int }}"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "tado_flow_temperature_current"
        device_class: temperature
        unit_of_measurement: "°C"
        value_template: "{{ value_json.autoAdaptation.maxFlowTemperature | default(0) | int }}"



```
Based on these, possible to add Flow temperature control to V3?
